# Generated by Django 5.2.1 on 2025-06-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='category',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='categories',
            field=models.ManyToManyField(related_name='category_offers', to='user_app.category'),
        ),
    ]
