# Generated by Django 5.1.7 on 2025-06-05 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_product_brand_productsizestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizestock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_stocks', to='user_app.product'),
        ),
        migrations.AlterField(
            model_name='productsizestock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
