# Generated by Django 5.1.7 on 2025-06-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='status',
        ),
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
