# Generated by Django 5.2.1 on 2025-07-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_wallettransaction_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_ACCEPTED', 'Return Accepted'), ('RETURN_REJECTED', 'Return Rejected')], default='ORDERED', max_length=20),
        ),
    ]
