# Generated by Django 5.2.1 on 2025-07-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
