# Generated by Django 5.2.1 on 2025-07-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_categoryoffer_is_delete_coupon_is_delete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
