# Generated by Django 5.2.1 on 2025-07-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_rename_is_delete_coupon_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryoffer',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='productoffer',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
