# Generated by Django 5.2.1 on 2025-07-18 16:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_alter_brand_logo_alter_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.png_unu5k8', max_length=255, null=True, verbose_name='images'),
        ),
    ]
