# Generated by Django 5.1.7 on 2025-06-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0025_order_cancel_reason_orderitem_cancel_reason_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailChangeToken',
        ),
    ]
