# Generated by Django 5.1.7 on 2025-06-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0028_order_country_order_district_order_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(max_length=1),
        ),
    ]
