# Generated by Django 5.2.1 on 2025-06-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0031_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
