# Generated by Django 5.2.1 on 2025-06-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0032_orderitem_return_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_return_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
